# Generated by Django 3.1.1 on 2020-09-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('mainPicSrc', models.CharField(max_length=256)),
                ('star', models.CharField(max_length=10)),
                ('summary', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('movies', models.ManyToManyField(to='myapp.Movie')),
            ],
        ),
    ]
